# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LightningUi.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QWidget)

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.setEnabled(True)
        Main.resize(320, 256)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QSize(320, 256))
        Main.setMaximumSize(QSize(320, 256))
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lightningDelayMinLabel = QLabel(self.centralwidget)
        self.lightningDelayMinLabel.setObjectName(u"lightningDelayMinLabel")
        self.lightningDelayMinLabel.setGeometry(QRect(180, 30, 61, 16))
        self.lightningDelayMinLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lightningDelayMinSpinbox = QDoubleSpinBox(self.centralwidget)
        self.lightningDelayMinSpinbox.setObjectName(u"lightningDelayMinSpinbox")
        self.lightningDelayMinSpinbox.setGeometry(QRect(250, 30, 61, 16))
        self.lightningDelayMinSpinbox.setDecimals(1)
        self.lightningDelayMinSpinbox.setSingleStep(0.200000000000000)
        self.lightningDelayMaxLabel = QLabel(self.centralwidget)
        self.lightningDelayMaxLabel.setObjectName(u"lightningDelayMaxLabel")
        self.lightningDelayMaxLabel.setGeometry(QRect(180, 50, 61, 16))
        self.lightningDelayMaxLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lightningDelayMaxSpinbox = QDoubleSpinBox(self.centralwidget)
        self.lightningDelayMaxSpinbox.setObjectName(u"lightningDelayMaxSpinbox")
        self.lightningDelayMaxSpinbox.setGeometry(QRect(250, 50, 61, 16))
        self.lightningDelayMaxSpinbox.setDecimals(1)
        self.lightningDelayMaxSpinbox.setSingleStep(0.200000000000000)
        self.buttonProgramStart = QPushButton(self.centralwidget)
        self.buttonProgramStart.setObjectName(u"buttonProgramStart")
        self.buttonProgramStart.setGeometry(QRect(200, 160, 111, 31))
        self.buttonProgramStop = QPushButton(self.centralwidget)
        self.buttonProgramStop.setObjectName(u"buttonProgramStop")
        self.buttonProgramStop.setGeometry(QRect(200, 200, 111, 31))
        self.lightningSettingsLabel = QLabel(self.centralwidget)
        self.lightningSettingsLabel.setObjectName(u"lightningSettingsLabel")
        self.lightningSettingsLabel.setGeometry(QRect(180, 10, 131, 20))
        font = QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QFont.PreferDefault)
        self.lightningSettingsLabel.setFont(font)
        self.lightningSettingsLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.thunderDelayMinSpinbox = QDoubleSpinBox(self.centralwidget)
        self.thunderDelayMinSpinbox.setObjectName(u"thunderDelayMinSpinbox")
        self.thunderDelayMinSpinbox.setGeometry(QRect(250, 100, 61, 16))
        self.thunderDelayMinSpinbox.setDecimals(1)
        self.thunderDelayMinSpinbox.setSingleStep(0.500000000000000)
        self.thunderDelayMaxSpinbox = QDoubleSpinBox(self.centralwidget)
        self.thunderDelayMaxSpinbox.setObjectName(u"thunderDelayMaxSpinbox")
        self.thunderDelayMaxSpinbox.setGeometry(QRect(250, 120, 61, 16))
        self.thunderDelayMaxSpinbox.setDecimals(1)
        self.thunderDelayMaxSpinbox.setSingleStep(0.500000000000000)
        self.thunderSettingsLabel = QLabel(self.centralwidget)
        self.thunderSettingsLabel.setObjectName(u"thunderSettingsLabel")
        self.thunderSettingsLabel.setGeometry(QRect(180, 80, 131, 20))
        self.thunderSettingsLabel.setFont(font)
        self.thunderSettingsLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.thunderDelayMaxLabel = QLabel(self.centralwidget)
        self.thunderDelayMaxLabel.setObjectName(u"thunderDelayMaxLabel")
        self.thunderDelayMaxLabel.setGeometry(QRect(180, 120, 61, 16))
        self.thunderDelayMaxLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.thunderDelayMinLabel = QLabel(self.centralwidget)
        self.thunderDelayMinLabel.setObjectName(u"thunderDelayMinLabel")
        self.thunderDelayMinLabel.setGeometry(QRect(180, 100, 61, 16))
        self.thunderDelayMinLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settingsDividerLine = QFrame(self.centralwidget)
        self.settingsDividerLine.setObjectName(u"settingsDividerLine")
        self.settingsDividerLine.setGeometry(QRect(180, 70, 131, 16))
        self.settingsDividerLine.setFrameShape(QFrame.HLine)
        self.settingsDividerLine.setFrameShadow(QFrame.Sunken)
        self.mixerSettingsLabel = QLabel(self.centralwidget)
        self.mixerSettingsLabel.setObjectName(u"mixerSettingsLabel")
        self.mixerSettingsLabel.setGeometry(QRect(10, 130, 161, 16))
        font1 = QFont()
        font1.setBold(True)
        self.mixerSettingsLabel.setFont(font1)
        self.volumeBackgroundLabel = QLabel(self.centralwidget)
        self.volumeBackgroundLabel.setObjectName(u"volumeBackgroundLabel")
        self.volumeBackgroundLabel.setGeometry(QRect(10, 150, 131, 16))
        self.volumeBackgroundLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.volumeEffectsSlider = QSlider(self.centralwidget)
        self.volumeEffectsSlider.setObjectName(u"volumeEffectsSlider")
        self.volumeEffectsSlider.setGeometry(QRect(10, 210, 161, 21))
        self.volumeEffectsSlider.setMaximum(100)
        self.volumeEffectsSlider.setSingleStep(5)
        self.volumeEffectsSlider.setValue(50)
        self.volumeEffectsSlider.setOrientation(Qt.Horizontal)
        self.volumeEffectsSlider.setTickPosition(QSlider.TicksAbove)
        self.volumeEffectsSlider.setTickInterval(10)
        self.volumeEffectsLabel = QLabel(self.centralwidget)
        self.volumeEffectsLabel.setObjectName(u"volumeEffectsLabel")
        self.volumeEffectsLabel.setGeometry(QRect(10, 190, 131, 16))
        self.volumeEffectsLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.volumeBackgroundSlider = QSlider(self.centralwidget)
        self.volumeBackgroundSlider.setObjectName(u"volumeBackgroundSlider")
        self.volumeBackgroundSlider.setGeometry(QRect(10, 170, 161, 21))
        self.volumeBackgroundSlider.setMaximum(100)
        self.volumeBackgroundSlider.setSingleStep(5)
        self.volumeBackgroundSlider.setValue(50)
        self.volumeBackgroundSlider.setOrientation(Qt.Horizontal)
        self.volumeBackgroundSlider.setTickPosition(QSlider.TicksAbove)
        self.volumeBackgroundSlider.setTickInterval(10)
        self.volumeBackgroundValue = QLabel(self.centralwidget)
        self.volumeBackgroundValue.setObjectName(u"volumeBackgroundValue")
        self.volumeBackgroundValue.setGeometry(QRect(140, 150, 31, 16))
        self.volumeBackgroundValue.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.volumeEffectsValue = QLabel(self.centralwidget)
        self.volumeEffectsValue.setObjectName(u"volumeEffectsValue")
        self.volumeEffectsValue.setGeometry(QRect(140, 190, 31, 16))
        self.volumeEffectsValue.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 141, 111))
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setMargin(0)
        self.label.setIndent(-1)
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Main)
        self.statusbar.setObjectName(u"statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)

        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Thunder & Lightning Controller", None))
#if QT_CONFIG(tooltip)
        self.lightningDelayMinLabel.setToolTip(QCoreApplication.translate("Main", u"Minimum range in seconds for a lightning strike", None))
#endif // QT_CONFIG(tooltip)
        self.lightningDelayMinLabel.setText(QCoreApplication.translate("Main", u"Delay Min", None))
#if QT_CONFIG(tooltip)
        self.lightningDelayMaxLabel.setToolTip(QCoreApplication.translate("Main", u"Maximum range in seconds for a lightning strike", None))
#endif // QT_CONFIG(tooltip)
        self.lightningDelayMaxLabel.setText(QCoreApplication.translate("Main", u"Delay Max", None))
        self.buttonProgramStart.setText(QCoreApplication.translate("Main", u"Start", None))
        self.buttonProgramStop.setText(QCoreApplication.translate("Main", u"Stop", None))
        self.lightningSettingsLabel.setText(QCoreApplication.translate("Main", u"Lightning Settings", None))
        self.thunderSettingsLabel.setText(QCoreApplication.translate("Main", u"Thunder Settings", None))
#if QT_CONFIG(tooltip)
        self.thunderDelayMaxLabel.setToolTip(QCoreApplication.translate("Main", u"Maximum range in seconds for thunder after a lightning stike", None))
#endif // QT_CONFIG(tooltip)
        self.thunderDelayMaxLabel.setText(QCoreApplication.translate("Main", u"Delay Max", None))
#if QT_CONFIG(tooltip)
        self.thunderDelayMinLabel.setToolTip(QCoreApplication.translate("Main", u"Minimum range in seconds for thunder after a lightning stike", None))
#endif // QT_CONFIG(tooltip)
        self.thunderDelayMinLabel.setText(QCoreApplication.translate("Main", u"Delay Min", None))
        self.mixerSettingsLabel.setText(QCoreApplication.translate("Main", u"Mixer Settings", None))
        self.volumeBackgroundLabel.setText(QCoreApplication.translate("Main", u"Background Volume", None))
        self.volumeEffectsLabel.setText(QCoreApplication.translate("Main", u"Effects Volume", None))
        self.volumeBackgroundValue.setText(QCoreApplication.translate("Main", u"50", None))
        self.volumeEffectsValue.setText(QCoreApplication.translate("Main", u"50", None))
        self.label.setText(QCoreApplication.translate("Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Thunder &amp; Lightning</span></p><p align=\"center\">Programmed by Bon</p></body></html>", None))
    # retranslateUi

